require:
  - ./lib/rubocop/cop/migrations/concurrent_index.rb
  - ./lib/rubocop/cop/migrations/default_value.rb

inherit_from:
  - lib/modified_cops.yml
  - lib/disabled_cops.yml

AllCops:
  DisplayCopNames: true
  TargetRailsVersion: 4.0
Rails:
  Enabled: true
